# Generated by Django 4.2.3 on 2023-07-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_task_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('task', models.TextField(verbose_name='Описание')),
                ('number', models.CharField(max_length=20, verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Новый запрос',
                'verbose_name_plural': 'Запросы',
            },
        ),
        migrations.RenameModel(
            old_name='Task',
            new_name='Course',
        ),
    ]
